services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    container_name: dbshop
    volumes:
      - ./postgres:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - 80:3000
    depends_on:
      - db
    container_name: frontend
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USER}